/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alerts: typeof import('./components/Alerts.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CodeDialog: typeof import('./components/dialogs/CodeDialog.vue')['default']
    Configurations: typeof import('./components/Configurations.vue')['default']
    ConfigurationType: typeof import('./components/create/configuration-type.vue')['default']
    ConfirmDialog: typeof import('./components/dialogs/ConfirmDialog.vue')['default']
    Groups: typeof import('./components/Groups.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LinkCreator: typeof import('./components/create/link-creator.vue')['default']
    LoaderDialog: typeof import('./components/dialogs/LoaderDialog.vue')['default']
    Processes: typeof import('./components/Processes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupervisorAction: typeof import('./components/SupervisorAction.vue')['default']
  }
}
